name: aac_command_line_support
description: A new Flutter project.
version: 0.0.2
homepage:



environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  args: ^2.3.1
  ansicolor: ^2.0.2
  resource_portable: ^3.1.0
  dart_console: ^4.1.0
  recase: ^4.1.0
  archive: ^3.6.1


  path: any
  http: ^1.2.2
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  m: main
