name: aac_command_line_support
description: A new Flutter project.
version: 0.0.1
homepage:



environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  args: ^2.3.1
  ansicolor: ^2.0.1
  resource_portable: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

executables:
  maac: main
